title: HELK index patterns and OSSEM field mappings
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - xpack-watcher
  - elastalert
  - elastalert-dsl
logsources:
  windows-application:
    product: windows
    service: application
    index: logs-endpoint-winevent-application-*
  windows-security:
    product: windows
    service: security
    index: logs-endpoint-winevent-security-*
  windows-sysmon:
    product: windows
    service: sysmon
    index: logs-endpoint-winevent-sysmon-*
  windows-system:
    product: windows
    service: system
    index: logs-endpoint-winevent-system-*
  windows-wmi:
    product: windows
    service: wmi
    index: logs-endpoint-winevent-wmiactivity-*
  windows-powershell:
    product: windows
    service: powershell
    index: logs-endpoint-winevent-powershell-*
  windows-powershell-classic:
    product: windows
    service: powershell-classic
    index: logs-endpoint-winevent-powershell-*
defaultindex: logs-*
fieldmappings:
  AccessList:
    EventID=4656: object_access_list
    EventID=4659: object_access_list
    EventID=4660: object_access_list
    EventID=4661: object_access_list
    EventID=4662: object_access_list
    EventID=4663: object_access_list
    EventID=5140: user_access_list
    EventID=5142: user_access_list
    EventID=5143: user_access_list
    EventID=5144: user_access_list
    EventID=5145: user_access_list
    EventID=5447: object_access_list
  AccessMask:
    EventID=4656: object_access_mask
    EventID=4659: object_access_mask
    EventID=4660: object_access_mask
    EventID=4661: object_access_mask
    EventID=4662: object_access_mask
    EventID=4663: object_access_mask
    EventID=4674: object_access_mask
    EventID=5140: share_access_mask
    EventID=5142: share_access_mask
    EventID=5143: share_access_mask
    EventID=5144: share_access_mask
    EventID=5145: share_access_mask
    EventID=5447: object_access_mask
  AccountName: user_name
  AllowedToDelegateTo: target_user_allowed_to_delegate
  AppCorrelationID: dsoperation_app_correlation_id
  AttributeLDAPDisplayName: dsobject_attribute_name
  AttributeSyntaxOID: dsobject_attribute_type
  AttributeValue: dsobject_attribute_value
  AuditPolicyChanges: policy_changes
  AuthenticationPackageName: logon_authentication_package
  CallingProcessName: process_path
  CallTrace: process_call_trace
  ClientAddress: src_ip_addr
  ClientIPAddress: src_ip_addr
  ClientIP: src_original_value
  CommandLine: process_command_line
  Company: file_company
  ComputerName: host_name
  Configuration:
    EventID=16: sysmon_configuration
  ConnectedViaIPAddress: dst_nat_ip_addr
  CurrentDirectory: process_current_directory
  Description: file_description
  DestAddress: dst_ip_addr
  Destination:
    EventID=20: wmi_consumer_destination
  DestinationHostname: dst_host_name
  DestinationIp: dst_ip_addr
  DestinationPort: dst_port
  DestinationPortName: dst_port_name
  DestinationIsIpv6: dst_is_ipv6
  Details:
    EventID=13: registry_key_value
  Device: device_name
  DisabledPrivilegeList:
    EventID=4703: target_user_disabled_privilege_list
  DSName: host_domain
  DSType: dsobject_domain_type
  EnabledPrivilegeList:
    EventID=4703: target_user_enabled_privilege_list
  EngineVersion: powershell.engine.version
  EventID: event_id
  EventType: event_type
  EventNamespace:
    EventID=19: wmi_namespace
  Filter:
    EventID=21: wmi_filter_path
  FailureCode: ticket_failure_code
  FileName: file_name
  FileVersion: file_version
  GrantedAccess: process_granted_access
  GroupName: group_name
  GroupSid: group_sid
  HiveName: hive_name
  HostVersion: powershell.host.version
  Image: process_path
  ImageLoaded:
    EventID=6: driver_loaded
    EventID=7: module_loaded
  Imphash: hash_imphash
  Initiated:
    EventID=3: network_initiated
  IntegrityLevel:
    EventID=1: process_integrity_level
  ipAddress: dst_ip_addr
  IpAddress: src_original_value
  IpAddresses:
    EventID=5168: ip_addresses
  IPString: src_ip_addr
  LaunchedViaIPAddress: dst_ip_addr
  LogonProcessName: logon_process_name
  LogonType: logon_type
  MachineIpAddress: dst_ip_addr
  MachineName: host_name
  Name:
    EventID=19: wmi_name
    EventID=20: wmi_name
  NewObjectDN: dsobject_new_dn
  NewProcessName: process_path
  NewName:
    EventID=14: registry_key_new_name
  ObjectClass: dsobject_class
  ObjectDN: dsobject_dn
  ObjectGUID: dsobject_guid
  ObjectName: object_name
  ObjectServer: object_server
  ObjectType: object_type
  ObjectValueName: object_value_name
  OldObjectDN: dsobject_old_dn
  OpCorrelationID: dsoperation_correlation_id
  Operation:
    EventID=19: wmi_operation
    EventID=20: wmi_operation
    EventID=21: wmi_operation
  OperationType:
    EventID=5136: dsoperation_type
    EventID=5137: dsoperation_type
    EventID=5138: dsoperation_type
    EventID=5139: dsoperation_type
    EventID=5141: dsoperation_type
    EventID=5169: dsoperation_type
    EventID=5170: dsoperation_type
    default: object_operation_type
  OriginalFileName: file_name_original
  ParentImage: process_parent_path
  ParentProcessName: process_parent_path
  PasswordLastSet: user_attribute_password_lastset
  Path: process_path
  ParentCommandLine: process_parent_command_line
  PipeName: pipe_name
  ProcessCommandLine: process_command_line
  ProcessName: process_path
  processPath: process_path
  ProcessPath: process_path
  Product: file_product
  Properties: object_properties
  Protocol:
    EventID=3: network_protocol
  Query:
    EventID=19: wmi_query
  RelativeTargetName: share_relative_target_name
  SamAccountName: user_attribute_samaccount_name
  SchemaVersion:
    EventID=4: sysmon_schema_version
  ServiceFileName: service_image_path
  ServiceName: service_name
  ShareName: share_name
  Signature: signature
  SignatureStatus: signature_status
  Signed: signed
  Source: source_name
  SourceAddress: src_ip_addr
  SourceHostname: src_host_name
  SourceIsIpv6: src_is_ipv6
  SourceImage: process_path
  SourceIp: src_ip_addr
  SourcePort: src_port
  SourcePortName: src_port_name
  StartAddress: thread_start_address
  StartFunction: thread_start_function
  StartModule: thread_start_module
  Status: event_status
  State:
    EventID=4: service_state
    EventID=16: sysmon_configuration_state
  SubjectUserName:
    EventID=4624: user_reporter_name
    EventId=4648: user_name
    EventID=5140: user_name
  TargetServer:
    EventID=5738: dst_original_value
    default: target_server_name
  TargetServerName: target_server_name
  TaskName: task_name
  TicketEncryptionType: ticket_encryption_type
  TicketOptions: ticket_options
  TargetFilename: file_name
  TargetImage: target_process_path
  TargetProcessAddress: thread_start_address
  TargetObject: registry_key_path
  TransactionId: object_transaction_guid
  Type:
    EventID=20: wmi_consumer_type
  User: user_account
  UserName: user_name
  Value:
    EventID=1102: dst_ip_addr
  Version:
    EventID=4: sysmon_version
  Workstation: src_host_name
  WorkstationName: src_host_name
  PrivilegeList:
    EventID=4656: object_privilege_list
    EventID=4660: object_privilege_list
    EventID=4661: object_privilege_list
    EventID=4662: object_privilege_list
    EventID=4663: object_privilege_list
    EventID=4672: logon_privilege_list
    EventID=4673: service_privilege_list
    EventID=4674: object_privilege_list
    EventID=4720: user_privilege_list
    EventID=4722: user_privilege_list
    EventID=4723: user_privilege_list
    EventID=4724: user_privilege_list
    EventID=4725: user_privilege_list
    EventID=4726: user_privilege_list
    EventID=4727: user_privilege_list
    EventID=4728: user_privilege_list
    EventID=4729: user_privilege_list
    EventID=4730: user_privilege_list
    EventID=4731: user_privilege_list
    EventID=4732: user_privilege_list
    EventID=4733: user_privilege_list
    EventID=4734: user_privilege_list
    EventID=4735: user_privilege_list
    EventID=4737: user_privilege_list
    EventID=4738: user_privilege_list
    EventID=4741: user_privilege_list
    EventID=4742: user_privilege_list
    EventID=4743: user_privilege_list
    EventID=4744: user_privilege_list
    EventID=4745: user_privilege_list
    EventID=4746: user_privilege_list
    EventID=4747: user_privilege_list
    EventID=4748: user_privilege_list
    EventID=4749: user_privilege_list
    EventID=4750: user_privilege_list
    EventID=4751: user_privilege_list
    EventID=4752: user_privilege_list
    EventID=4753: user_privilege_list
    EventID=4754: user_privilege_list
    EventID=4755: user_privilege_list
    EventID=4756: user_privilege_list
    EventID=4757: user_privilege_list
    EventID=4758: user_privilege_list
    EventID=4759: user_privilege_list
    EventID=4760: user_privilege_list
    EventID=4761: user_privilege_list
    EventID=4762: user_privilege_list
    EventID=4763: user_privilege_list
    EventID=4764: user_privilege_list
  UtcTime: '@timestamp'
  EventTime: '@timestamp'
