alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential recon for domain admins via net samrp
filter:
- query:
    query_string:
      query: (event_id:1 AND process_name:("net.exe" OR "net1.exe") AND process_command_line:"domain admins")
index: logs-endpoint-winevent-sysmon-*
name: Windows-net-domain-admins_0
priority: 2
realert:
  minutes: 0
type: any