alert:
- debug
- email
email: 
      - "support@infinitehosting.uk"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "support@infinitehosting.uk"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential use of rubeus via the trusted logon process
filter:
- query:
    query_string:
      query: (event_id:4611 AND logon_process_name:user32logonprocesss)
index: logs-endpoint-winevent-security-*
name: Windows-Rubeus-logon-process_0
priority: 2
realert:
  minutes: 0
type: any
