alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential lateral movement via dcom
filter:
- query:
    query_string:
      query: (event_id:1 AND process_name:("outlook.exe" OR "excel.exe" OR "winword.exe" OR "powerpnt.exe" OR "mmc.exe") AND process_command_line:*Embedding*)
index: logs-endpoint-winevent-sysmon-*
name: Windows-dcom-lm_0
priority: 2
realert:
  minutes: 0
type: any