alert:
- debug
description: Detects potential DCSync from non-dcs
filter:
- query:
    query_string:
      query: (event_id:4662 AND NOT user_name.keyword:*$ AND object_operation_type:"Object Access" AND object_access_mask:"0x100" AND object_properties:("*1131f6aa-9c07-11d1-f79f-00c04fc2dcd2*" OR "*1131f6ad-9c07-11d1-f79f-00c04fc2dcd2*" OR "*89e95b76-444d-4c62-991a-0facbeda640c*"))
index: logs-endpoint-winevent-security-*
name: Windows-dcsync-non-dc_0
priority: 2
realert:
  minutes: 0
type: any