alert:
- debug
- email
email: 
      - "support@infinitehosting.uk"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "support@infinitehosting.uk"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential calls to DCs via Kerberos port from non lsass
filter:
- query:
    query_string:
      query: (event_id:3 AND NOT process_name:"lsass.exe" AND dst_port:88)
index: logs-endpoint-winevent-sysmon-*
name: Windows-Kerberos-call-DC-no-lsass_0
priority: 2
realert:
  minutes: 0
type: any