alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential DCSync backdoor user
filter:
- query:
    query_string:
      query: (event_id:5136  AND dsobject_attribute_name:"ntsecuritydescriptor" AND dsobject_attribute_value:("1131f6aa-9c07-11d1-f79f-00c04fc2dcd2" OR "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2" OR "89e95b76-444d-4c62-991a-0facbeda640c"))
index: logs-endpoint-winevent-security*
name: Windows-DCSync-backdoor-user_0
priority: 2
realert:
  minutes: 0
type: any
