alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential scriptable handlers
filter:
- query:
    query_string:
      query: ((process_name:"mshta.exe" OR process_name:"rundll32.exe") AND (process_command_line:*vbscript* OR process_command_line:*javascript*))
index: logs-endpoint-winevent-sysmon-*
name: Windows-scriptable-handlers_0
priority: 2
realert:
  minutes: 0
type: any