alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential suspicious powershell parameters
filter:
- query:
    query_string:
      query: (process_path:("*\\Powershell.exe") AND event_id:"1" AND process_command_line.keyword:( /.*\-w.*h.*/ /.*\-NoP.*/ /.*\-noni.*/ /.*\-ec.*/ /.*\-en.*/))
index: logs-endpoint-winevent-*
name: Windows-Suspicious-Powershell-commands_0
priority: 2
realert:
  minutes: 0
type: any
