alert:
- debug
- email
email: 
      - "your@emailaddress.com"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "your@emailaddress.com"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects use of winrm over the network
filter:
- query:
    query_string:
      query: (event_id:1 AND process_parent_name:"wsmprovhost.exe")
index: logs-endpoint-winevent-sysmon-*
name: Windows-wsmprovhost-winrm_0
priority: 2
realert:
  minutes: 0
type: any