alert:
- debug
- email
email: 
      - "support@infinitehosting.uk"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "support@infinitehosting.uk"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential Csharp compiling
filter:
- query:
    query_string:
      query: (event_id:1 AND process_parent_command_line:"csc.exe" AND process_command_line:"cvtres")
index: logs-endpoint-winevent-sysmon-*
name: Windows-csharp-compile_0
priority: 2
realert:
  minutes: 0
type: any