alert:
- debug
- email
email: 
      - "support@infinitehosting.uk"
smtp_host: "smtp.outlook.com" #for O365 email addresses
smtp_port: 587 #for O365 email addresses
smtp_ssl: true
from_addr: "support@infinitehosting.uk"
smtp_auth_file: "/etc/elastalert/smtp_auth_file.yaml"
description: Detects potential psexec via powershell module
filter:
- query:
    query_string:
      query: (event_id:7045 AND service_image_path:(comspec OR powershell))
index: logs-endpoint-winevent-system-*
name: Windows-System-Psexec-Powershell-Module_0
priority: 2
realert:
  minutes: 0
type: any